'use client';
import Link from 'next/link';
import {useState,type FormEvent} from 'react';
import {ANGLES,CATEGORIES,STATUSES,METHODOLOGY,canTransition,classify,outreach,scorecard,type AuthorityReport,type Prospect,type Research} from './model';
const external=(href:string,label:string)=><a href={href} target="_blank" rel="noopener noreferrer">{label} ↗</a>;
const blank:Research={country:'Brasil',language:'pt-BR',brazil:false,football:false,odds:false,editorial:false,active:false,articleUrl:'',articleTitle:'',articleDate:null,sectionUrl:'',contactAlternative:'',evidenceUrl:'',checkedAt:'',audienceSignal:'NOT_AVAILABLE',fit:'',linkability:'',spamFlags:[],mentionStatus:'UNKNOWN',competitorEvidence:'NOT_AVAILABLE'};
type Action=(body:Record<string,unknown>)=>Promise<void>;
export function AuthorityWorkspace({initial}:{initial:AuthorityReport}){
 const [report,setReport]=useState(initial),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[status,setStatus]=useState(''),[priority,setPriority]=useState(''),[category,setCategory]=useState(''),[query,setQuery]=useState(''),[selected,setSelected]=useState(''),[showQa,setShowQa]=useState(false),[fallback,setFallback]=useState('');
 const action:Action=async body=>{setBusy(true);setMessage('');try{const response=await fetch('/api/owner/growth/authority',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),result=await response.json();if(!response.ok)throw Error(result.error??'Falha ao salvar');const fresh=await fetch('/api/owner/growth/authority');if(!fresh.ok)throw Error('Salvo; recarregue a página.');setReport(await fresh.json());setMessage('Salvo. Histórico preservado. Nenhuma mensagem foi enviada.');}catch(e){setMessage(e instanceof Error?e.message:'Falha ao salvar');}finally{setBusy(false);}};
 async function copy(value:string){try{await navigator.clipboard.writeText(value);setMessage('Copiado. Envio é manual.');}catch{setFallback(value);setMessage('Selecione o texto abaixo e copie manualmente.');}}
 const prospects=report.prospects.filter(p=>!p.isQa),links=report.links.filter(l=>!l.isQa),live=links.filter(l=>l.state==='LIVE'),card=scorecard(report),now=Date.parse(report.generatedAt),sent=new Set(report.events.filter(e=>e.toStatus==='CONTACTED'&&prospects.some(p=>p.id===e.prospectId)).map(e=>e.prospectId)),responded=new Set(report.events.filter(e=>['INTERESTED','DECLINED'].includes(e.toStatus??'')&&sent.has(e.prospectId)).map(e=>e.prospectId));
 const filtered=report.prospects.filter(p=>(showQa||!p.isQa)&&(!status||p.status===status)&&(!priority||p.priority===priority)&&(!category||p.category===category)&&`${p.name} ${p.domain}`.toLowerCase().includes(query.toLowerCase()));const p=report.prospects.find(p=>p.id===selected);
 return <main className="owner-health authority"><header className="owner-health-header"><div><p>BRASIL · RELAÇÕES EDITORIAIS</p><h1>Autoridade & distribuição</h1><p>Pesquisar → preparar → contato manual → verificar → medir</p></div><nav className="owner-health-actions"><Link href="/owner/growth">Growth Queue</Link><Link href="/owner/growth/dashboard">Growth dashboard</Link><Link href="/owner/growth/seo">SEO</Link></nav></header>
 <p className="owner-health-notice">Sem envio automático, compra de links ou “Domain Authority”. GSC Links / provedor de backlinks: NOT_AVAILABLE. Esta é a base conhecida, não um censo da web.</p>
 <div className="owner-health-cards">{Object.entries({'Domínios com link LIVE verificado':new Set(live.map(l=>l.domain)).size,'Links novos · 7 dias':links.filter(l=>l.firstSeenAt&&now-Date.parse(l.firstSeenAt)<7*86400000).length,'Links novos · 28 dias':links.filter(l=>l.firstSeenAt&&now-Date.parse(l.firstSeenAt)<28*86400000).length,'Links removidos':links.filter(l=>l.state==='REMOVED').length,'Prospects':prospects.length,'Contatos registrados':sent.size,'Respostas explícitas':responded.size,'Sessões referral · 28 dias':report.referrals.reduce((n,r)=>n+r.sessions,0),'Cliques para casas · referral':report.referrals.reduce((n,r)=>n+r.clicks,0)}).map(([label,value])=><div className="owner-health-card" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
 <p>Taxa de resposta (INTERESTED ou DECLINED / domínios contatados): {sent.size?`${Math.round(responded.size/sent.size*100)}%`:'sem base'}. Receita/FTD: não atribuídos por este relatório. Links e visitas não provam receita.</p>
 <section><h2>Scorecard semanal</h2><div className="owner-health-cards">{Object.entries(card).map(([name,items])=><div className="owner-health-card" key={name}><h3>{name.toUpperCase()}</h3>{items.length?<ul>{items.slice(0,20).map((item,i)=><li key={i}>{item}</li>)}</ul>:<p>Nenhuma evidência nesta categoria.</p>}</div>)}</div></section>
 <section><h2>Pipeline e prioridades</h2><p>{STATUSES.map(s=>`${s}: ${prospects.filter(p=>p.status===s).length}`).join(' · ')}</p><p>{['HIGH','MEDIUM','LOW','REJECT'].map(s=>`${s}: ${prospects.filter(p=>p.priority===s).length}`).join(' · ')}</p><p>{CATEGORIES.map(c=>`${c}: ${prospects.filter(p=>p.category===c).length}`).join(' · ')}</p></section>
 <section><h2>Follow-ups vencidos / hoje</h2>{prospects.filter(p=>p.followUpOn&&p.followUpOn<=report.generatedAt.slice(0,10)&&!['REJECTED','DECLINED','LINK_LIVE'].includes(p.status)).map(p=><button disabled={busy} key={p.id} onClick={()=>setSelected(p.id)}>{p.name} · {p.followUpOn}</button>)}</section>
 <details><summary>Adicionar prospect</summary><ProspectForm busy={busy} action={action}/></details>
 <section><h2>Prospects pesquisados</h2><div className="owner-health-filters"><label>Buscar<input value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos</option>{STATUSES.map(s=><option key={s}>{s}</option>)}</select></label><label>Prioridade<select value={priority} onChange={e=>setPriority(e.target.value)}><option value="">Todas</option>{['HIGH','MEDIUM','LOW','REJECT'].map(s=><option key={s}>{s}</option>)}</select></label><label>Categoria<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">Todas</option>{CATEGORIES.map(s=><option key={s}>{s}</option>)}</select></label><label><input type="checkbox" checked={showQa} onChange={e=>setShowQa(e.target.checked)}/>Mostrar QA</label></div><p>{filtered.length} resultados · até 1.000 registros</p><div className="authority-prospects">{filtered.map(p=><button aria-pressed={selected===p.id} disabled={busy} key={p.id} onClick={()=>setSelected(p.id)}><strong>{p.name}</strong><span>{p.domain}</span><small>{p.priority} · {p.status}{p.isQa?' · QA':''}</small></button>)}</div></section>
 <p role="status" aria-live="polite">{busy?'Salvando…':message}</p>{fallback?<label>Texto para copiar<textarea readOnly value={fallback} onFocus={e=>e.target.select()}/></label>:null}
 {p?<section className="authority-detail" key={p.id}><h2>{p.name}</h2><p>{p.domain} · {p.priority} · {p.category}</p><ul>{classify(p.research,!!(p.contactUrl||p.email||p.research.contactAlternative)).reasons.map(s=><li key={s}>{s}</li>)}</ul><p>{p.research.fit}</p><p>Linkabilidade: {p.research.linkability} · Audiência: {p.research.audienceSignal}</p><p>Menção LivaSports: {p.research.mentionStatus} · Concorrentes: {p.research.competitorEvidence}</p><p>Verificado em: {p.research.checkedAt} · Artigo: {p.research.articleDate??'data não confirmada'}</p>
 <div className="owner-health-actions">{p.contactUrl?external(p.contactUrl,'Abrir contato'):null}{p.research.articleUrl?external(p.research.articleUrl,'Artigo de referência'):null}{external(p.research.evidenceUrl,'Evidência')}{external(p.targetUrl,'Ativo LivaSports')}{p.email?<button onClick={()=>void copy(p.email!)}>Copiar email</button>:null}</div><p>Contato alternativo: {p.research.contactAlternative||'não confirmado'}</p>
 <h3>Mensagem editorial · revisão humana antes do envio</h3>{Object.entries(outreach(p)).map(([key,value])=><div key={key}><label>{key}<textarea readOnly value={value}/></label><button onClick={()=>void copy(value)}>Copiar {key}</button></div>)}
 <StatusForm p={p} busy={busy} action={action}/><form onSubmit={e=>{e.preventDefault();void action({action:'follow-up',id:p.id,date:new FormData(e.currentTarget).get('date')});}}><label>Próximo follow-up<input type="date" name="date" defaultValue={p.followUpOn??''}/></label><button disabled={busy}>Salvar follow-up</button></form>
 <h3>Registrar backlink para verificação</h3><p>O registro começa em UNKNOWN. Somente um link observado pelo monitor pode ser marcado LINK_LIVE.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void action({action:'link',id:p.id,sourceUrl:f.get('sourceUrl'),targetUrl:f.get('targetUrl'),note:f.get('note')});}}><label>URL da publicação<input name="sourceUrl" type="url" required/></label><label>Destino LivaSports<input name="targetUrl" type="url" defaultValue={p.targetUrl} required/></label><label>Resultado / observação<input name="note" maxLength={2000}/></label><button disabled={busy}>Registrar backlink</button></form>
 <details><summary>Editar pesquisa, contato e notas</summary><ProspectForm key={p.id+report.generatedAt} p={p} busy={busy} action={action}/></details><h3>Histórico preservado</h3><ol>{report.events.filter(e=>e.prospectId===p.id).map(e=><li key={e.id}>{e.occurredAt} · {e.kind} · {e.fromStatus} → {e.toStatus} · {e.note}</li>)}</ol></section>:null}
 <section><h2>Links conhecidos</h2><p>Verificação semanal por link, rodada diária limitada a 5 domínios / 15 requisições externas + 1 consulta ao ativo próprio. Bloqueios e falhas = UNKNOWN. QA excluído.</p>{links.length?links.map(l=><article className="owner-health-card" key={l.id}><h3>{l.domain} · {l.state}</h3>{external(l.sourceUrl,'Origem')}{external(l.targetUrl,'Destino')}<p>Âncora: {l.anchor??'não observada'} · rel: {l.rel??'unknown'} · HTTP {l.httpStatus??'—'}</p><p>Primeiro: {l.firstSeenAt??'não observado'} · Última checagem: {l.lastCheckedAt??'pendente'}</p></article>):<p>Nenhum backlink registrado. Não implica ausência de links na web.</p>}<h3>Rodadas do monitor</h3>{report.runs.map(r=><div key={r.day}><p>{r.day} · {r.state} · {r.linksChecked} links · {r.requests} requisições</p>{r.assetChecks?.map(a=><p key={a.url}>Ativo: {a.status===200?'HTTP 200':a.status??'UNKNOWN'} · {a.url}</p>)}</div>)}</section>
 <section><h2>Impacto referral · últimos 28 dias</h2><p>HUMAN em sessão e evento; OWNER, QA e BOT excluídos. Domínio referral não equivale a backlink confirmado. Sessões contadas pela data de início; eventos pela data de ocorrência.</p><div className="owner-health-scroll"><table className="owner-health-table"><thead><tr>{['Domínio','Landing / ativo','Sessões','Engajadas','Match views','Odds','Slip','Cliques'].map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{report.referrals.map((r,i)=><tr key={i}><td>{r.domain}</td><td>{r.landingPath}</td><td>{r.sessions}</td><td>{r.engaged}</td><td>{r.matchViews}</td><td>{r.odds}</td><td>{r.slipAdds}</td><td>{r.clicks}</td></tr>)}</tbody></table></div></section>
 <ImpactSummary report={report}/>
 {showQa?<section><h2>Backlinks QA · fora dos indicadores</h2>{report.links.filter(l=>l.isQa).map(l=><p key={l.id}>{l.sourceUrl} → {l.targetUrl} · {l.state}</p>)}</section>:null}
 <section><h2>Ativo de citação</h2>{external(METHODOLOGY,'Metodologia de comparação de odds')}<p>Protocolo de consulta e citação; usa a rota canônica existente. Sem previsões, dados históricos inventados ou redistribuição de dados de terceiros.</p></section>
 <footer>Envio sempre manual. Sem compra de dofollow, PBN, diretórios genéricos, autores falsos ou dados privados. Revisar pertinência antes de cada contato. Não repetir follow-up sem interesse.</footer></main>;
}
function StatusForm({p,busy,action}:{p:Prospect;busy:boolean;action:Action}){return <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void action({action:'status',id:p.id,status:f.get('status'),confirmSent:f.get('sent')==='on',note:f.get('note')});}}><h3>Status atual: {p.status}</h3><label>Novo status<select name="status" required><option value="">Selecione</option>{STATUSES.filter(s=>canTransition(p.status,s)).map(s=><option key={s}>{s}</option>)}</select></label><label><input type="checkbox" name="sent"/>Já enviei a mensagem manualmente (obrigatório para CONTACTED)</label><label>Resposta / resultado / nota<input name="note" maxLength={2000}/></label><button disabled={busy}>Atualizar status</button></form>;}
function ImpactSummary({report}:{report:AuthorityReport}){
 const groups=(key:'domain'|'landingPath'|'category')=>{const data=new Map<string,{sessions:number;clicks:number}>();for(const r of report.referrals){const label=key==='category'?report.prospects.find(p=>!p.isQa&&p.domain===r.domain)?.category??'OTHER':r[key],old=data.get(label)??{sessions:0,clicks:0};old.sessions+=r.sessions;old.clicks+=r.clicks;data.set(label,old);}return [...data].sort((a,b)=>b[1].clicks-a[1].clicks||b[1].sessions-a[1].sessions);};
 return <section><h2>Onde o tráfego gera impacto · 28 dias</h2>{([['domain','Domínios'],['landingPath','Landing pages / ativos'],['category','Categorias']] as const).map(([key,title])=><div key={key}><h3>{title} · cliques, depois sessões</h3>{groups(key).length?<ul>{groups(key).slice(0,20).map(([label,v])=><li key={label}>{label}: {v.clicks} cliques · {v.sessions} sessões</li>)}</ul>:<p>Sem tráfego HUMAN atribuído.</p>}</div>)}</section>;
}
function ProspectForm({p,busy,action}:{p?:Prospect;busy:boolean;action:Action}){
 const r=p?.research??blank;
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),research={...r};for(const key of ['country','language','articleUrl','articleTitle','sectionUrl','contactAlternative','evidenceUrl','audienceSignal','fit','linkability','competitorEvidence'] as const)research[key]=String(f.get(key)??'');research.articleDate=String(f.get('articleDate')??'')||null;for(const key of ['brazil','football','odds','editorial','active'] as const)research[key]=f.get(key)==='on';research.spamFlags=String(f.get('spamFlags')??'').split('\n').map(s=>s.trim()).filter(Boolean);
 const body:Record<string,unknown>={action:p?'edit':'create',research};for(const key of ['name','category','angle','contactUrl','email','targetUrl','notes'] as const)body[key]=f.get(key);if(p){body.id=p.id;body.followUpOn=p.followUpOn;}else{body.url=f.get('url');body.isQa=f.get('isQa')==='on';}void action(body);}
 return <form onSubmit={submit}><label>Nome<input name="name" required maxLength={160} defaultValue={p?.name}/></label>{!p?<label>Site HTTPS<input name="url" type="url" required/></label>:null}<label>Categoria<select name="category" defaultValue={p?.category}>{CATEGORIES.map(s=><option key={s}>{s}</option>)}</select></label><label>Ângulo<select name="angle" defaultValue={p?.angle}>{ANGLES.map(s=><option key={s}>{s}</option>)}</select></label>
 {([['contactUrl','Página pública de contato',p?.contactUrl],['email','Email profissional público',p?.email],['targetUrl','Ativo LivaSports',p?.targetUrl??METHODOLOGY],['notes','Notas',p?.notes]] as const).map(([name,label,value])=><label key={name}>{label}<input name={name} defaultValue={value??''} required={name==='targetUrl'} maxLength={2000}/></label>)}
 {(['country','language','sectionUrl','articleUrl','articleTitle','articleDate','contactAlternative','evidenceUrl','audienceSignal','fit','linkability','competitorEvidence'] as const).map(key=><label key={key}>{key}<input name={key} type={key==='articleDate'?'date':'text'} defaultValue={r[key]??''} required={['country','language','sectionUrl','evidenceUrl','fit'].includes(key)} maxLength={key==='fit'||key==='competitorEvidence'?1000:2000}/></label>)}
 {(['brazil','football','odds','editorial','active'] as const).map(key=><label key={key}><input name={key} type="checkbox" defaultChecked={r[key]}/>{key} · evidência confirmada manualmente</label>)}<label>Sinais de spam / risco (um por linha; qualquer sinal classifica REJECT)<textarea name="spamFlags" defaultValue={r.spamFlags.join('\n')}/></label>{!p?<label><input type="checkbox" name="isQa"/>Registro QA · excluído dos indicadores</label>:null}<button disabled={busy}>Salvar prospect</button></form>;
}
