import {METHODOLOGY,type Category,type Research} from './model';
/** Public editorial research, 2026-09-27. URLs were observed on the publishers' own sites.
 * No traffic estimates, private emails, guaranteed placement or assumed competitor gaps.
 * Date null means the publication date has not been independently extracted. */
type Entry=[name:string,site:string,category:Category,article:string,title:string,contact:string,fit:string];
const entries:Entry[]=[
 ['GOAL Brasil','https://www.goal.com/br','BETTING_EDITORIAL','https://www.goal.com/br/not%C3%ADcias/danilo-santos-craque-selecao-brasileira-conquistou-carlo-ancelotti-apenas-95-minutos/blta1838de398c2fac0','Danilo e seu início na seleção brasileira','https://www.goal.com/br/contato','Redação brasileira e análise esportiva. Sugestões de pauta têm email público; oferecer referência, não campanha comercial.'],
 ['Revista Colorada','https://www.revistacolorada.com.br/','CLUB_FAN','https://www.revistacolorada.com.br/inter-possui-retrospecto-positivo-contra-o-corinthians-recentemente/','Retrospecto recente de Internacional e Corinthians','https://www.revistacolorada.com.br/sobre-contato/','Cobertura do Internacional; pautas de confronto e agenda podem citar consulta metodológica.'],
 ['APWin Brasil','https://www.apwin.com/br/','DATA_ANALYTICS','https://www.apwin.com/br/palpites/wydad-casablanca-x-widad-temara-palpite-campeonato-marroquino-26-09-2026/','Prévia de Wydad Casablanca x Widad Témara','https://www.apwin.com/br/contato/','Estatísticas e prévias em PT-BR. É também concorrente: fit moderado, propor diálogo sobre método sem copiar prognósticos.'],
 ['UOL / Mauro Cezar Pereira','https://www.uol.com.br/esporte/futebol/colunas/mauro-cezar-pereira/','JOURNALIST','https://www.uol.com.br/esporte/futebol/colunas/mauro-cezar-pereira/2026/09/21/rodada-do-brasileiro-supera-a-media-de-uma-hora-de-bola-rolando-por-partida.htm','Rodada do Brasileiro supera uma hora de bola rolando por partida','https://linktr.ee/maurocezar000','Página profissional de jornalista com pauta de dados de futebol. Linktree público é alternativa profissional, não email editorial confirmado. Contar UOL apenas uma vez.'],
 ['Nosso Palestra','https://nossopalestra.com.br/','CLUB_FAN','https://nossopalestra.com.br/noticias/com-11-ausencias-palmeiras-da-sequencia-em-preparacao-para-volta-do-brasileirao/','Palmeiras se prepara para a volta do Brasileirão','https://nossopalestra.com.br/fale-conosco/','Cobertura própria do Palmeiras; oferecer método de consulta para prévias, não previsões.'],
 ['NETVASCO','https://www.netvasco.com.br/','CLUB_FAN','https://www.netvasco.com.br/n/393358/sub-20-vasco-vence-o-botafogo-por-3-a-0-pela-taca-guanabara','Vasco vence o Botafogo pela Taça Guanabara Sub-20','https://www.netvasco.com.br/faq/','Arquivo e agenda vascaína. Priorizar recursos de consulta; FAQ informa que não troca banners.'],
 ['SuperVasco','https://www.supervasco.com/','CLUB_FAN','https://www.supervasco.com/destaque/41198/','Novo investidor do Vasco visita o CT','https://www.supervasco.com/contato/','Serviço ao leitor vascaíno; confirmar interesse editorial antes de propor odds.'],
 ['São Paulo Blog','https://saopaulo.blog/','CLUB_FAN','https://saopaulo.blog/tabela-classificacao-sao-paulo-brasileirao-2026/','Tabela e classificação do São Paulo no Brasileirão 2026','https://saopaulo.blog/contato/','Página de serviço ao torcedor; referência observada é uma tabela atualizável, não uma reportagem datada.'],
 ['Diário do Peixe','https://www.diariodopeixe.com.br/','CLUB_FAN','https://www.diariodopeixe.com.br/noticias/com-vantagem-santos-recebe-riopretano-e-catanduvense-por-decisao-no-paulista-sub-13-e-sub-14/','Santos recebe Riopretano e Catanduvense por decisão na base','https://www.diariodopeixe.com.br/contato/','Redação especializada no Santos; proposta de referência metodológica para consultas a jogos profissionais. Não prometer odds da base.'],
 ['NETFLU','https://www.netflu.com.br/','CLUB_FAN','https://www.netflu.com.br/calendario-da-libertadores-torneio-volta-a-ter-bola-rolando-em-outubro-final-e-em-novembro/','Calendário da Libertadores: retorno em outubro e final em novembro','https://www.netflu.com.br/apostas/contato/','Agenda do Fluminense e Libertadores; contato observado é da seção de apostas, confirmar encaminhamento editorial.'],
 ['FogãoNET','https://www.fogaonet.com/','CLUB_FAN','https://www.fogaonet.com/noticias-do-botafogo/tite-ajusta-posicionamentos-primeira-semana-data-fifa-botafogo-projeta-medina-esquerda/','Tite ajusta posicionamentos no Botafogo durante a data Fifa','https://www.fogaonet.com/contato/','Noticiário do Botafogo; recurso complementar para prévias de partidas, sem alegar informação exclusiva.'],
 ['ecbahia','https://www.ecbahia.com/','CLUB_FAN','https://www.ecbahia.com/divisoes-de-base/bahia-e-campeao-nordeste-sub-20/','Bahia conquista o Nordestão Sub-20','https://www.ecbahia.com/contato/','Portal especializado no Bahia; oferecer metodologia para pautas profissionais, não cobertura de odds da base.'],
 ['Meu Timão','https://www.meutimao.com.br/','CLUB_FAN','https://www.meutimao.com.br/noticias-do-corinthians/540903/corinthians-tropeca-em-casa-contra-o-sao-paulo-e-sai-em-desvantagem-na-final-do-brasileirao-feminino','Corinthians sai em desvantagem na final do Brasileirão Feminino','https://www.meutimao.com.br/contato/','Redação, agenda e comunidade corinthiana; formulário editorial público. Não usar fórum para distribuir links.'],
 ['Coluna do Fla','https://colunadofla.com/','CLUB_FAN','https://colunadofla.com/2026/09/qual-e-o-proximo-jogo-do-flamengo-5/','Qual é o próximo jogo do Flamengo?','https://colunadofla.com/contato/','Artigo de serviço diretamente alinhado a descoberta de partidas do Flamengo.'],
 ['Trivela','https://trivela.com.br/','BETTING_EDITORIAL','https://trivela.com.br/europa/manchester-city-punicoes-pontos-equipes-europa/','Maiores punições de pontos na história do futebol','https://trivela.com.br/contato/','Futebol brasileiro/internacional e seção editorial de odds; metodologia ajuda a distinguir preço de previsão. Também publica newsletter.'],
 ['Lance!','https://www.lance.com.br/','FOOTBALL_MEDIA','https://www.lance.com.br/selecao-brasileira/ancelotti-testa-sete-mudancas-na-escalacao-da-selecao-para-segundo-jogo-com-australia.html','Ancelotti testa mudanças para o segundo jogo com a Austrália','https://www.lance.com.br/fale-conosco','Redação esportiva nacional; recurso de checagem para cobertura de partidas e mercados.'],
 ['UmDois Esportes','https://www.umdoisesportes.com.br/','REGIONAL','https://www.umdoisesportes.com.br/parana-clube/parana-clube-pode-ser-primeiro-classificado-copa-parana-matematica/','Paraná Clube pode ser o primeiro classificado na Copa Paraná','https://www.umdoisesportes.com.br/contacto/','Cobertura paranaense, com seção de dados e apostas. Não prometer cobertura de todas as divisões.'],
 ['NE45','https://ne45.com.br/','NEWSLETTER_CREATOR','https://ne45.com.br/2026/09/26/floresta-santa-cruz-empate-acesso-serie-b/','Santa Cruz empata com Floresta e se aproxima do acesso','https://ne45.com.br/quem-somos/','Projeto editorial e de podcasts do futebol nordestino. Contato via página do projeto; não é formulário dedicado confirmado.'],
 ['Esporte News Mundo','https://esportenewsmundo.com.br/','FOOTBALL_MEDIA','https://esportenewsmundo.com.br/de-virada-sao-paulo-quebra-invencibilidade-do-corinthians-em-itaquera-e-vence-primeiro-jogo-da-final-do-brasileirao-feminino/','São Paulo vence o Corinthians na ida da final feminina','https://esportenewsmundo.com.br/sobre/','Cobertura de clubes e partidas; oferecer referência de metodologia para repórteres.'],
 ['Itatiaia','https://www.itatiaia.com.br/esportes/','REGIONAL','https://www.itatiaia.com.br/esportes/futebol/futebol-nacional/futebol-mineiro/america/america-capitao-segue-fora-e-zagueiro-pode-retornar-para-duelo-pela-serie-b/','América se prepara para duelo pela Série B','https://www.itatiaia.com.br/contato/','Cobertura mineira de Atlético, Cruzeiro e América; forte pertinência regional e de agenda.'],
 ['Gazeta Esportiva','https://www.gazetaesportiva.com/','FOOTBALL_MEDIA','https://www.gazetaesportiva.com/campeonatos/brasileirao-feminino/corinthians-x-sao-paulo-ida-final-brasileirao-feminino-26-09-2026/','São Paulo abre vantagem na final do Brasileiro feminino','https://www.tvgazeta.com.br/fale-conosco/','Redação paulista e nacional; contato institucional do grupo, solicitar encaminhamento à editoria esportiva.'],
 ['Bahia Notícias','https://www.bahianoticias.com.br/esportes','REGIONAL','https://www.bahianoticias.com.br/esportes/vitoria/31593-vitoria-vence-jogo-treino-contra-o-five-por-3-a-0-e-segue-na-preparacao-para-enfrentar-a-chapecoense','Vitória se prepara para enfrentar a Chapecoense','https://www.bahianoticias.com.br/fale-conosco','Agenda de Bahia e Vitória; pertinência regional para descoberta de partidas profissionais.'],
 ['Correio da Bahia','https://www.correio24horas.com.br/esportes','REGIONAL','https://www.correio24horas.com.br/esportes/gigante-nordestino-fica-a-um-empate-de-voltar-a-serie-b-apos-dez-anos-0926','Clube nordestino fica a um empate do acesso à Série B','https://www.correio24horas.com.br/atendimento/atendimento-0623','Jornal regional com cobertura de acesso e futebol baiano; contato geral requer encaminhamento à redação.'],
 ['Footure','https://footure.com.br/','DATA_ANALYTICS','https://footure.com.br/da-posse-ao-ataque-direto-como-franclim-carvalho-mudou-o-botafogo-em-2026/','Da posse ao ataque direto: o Botafogo em 2026','https://footure.com.br/contato/','Análise tática, dados, podcasts e newsletter. Sugerir recurso de consulta metodológica, não confundir odds com análise tática.'],
 ['Verminosos por Futebol','https://www.verminososporfutebol.com.br/','NEWSLETTER_CREATOR','https://www.verminososporfutebol.com.br/vizinhos-de-muro-uma-serie-de-times-da-argentina-com-estadios-colados-em-rivais/','Estádios vizinhos de rivais argentinos','https://www.verminososporfutebol.com.br/quem-somos/','Projeto autoral de cultura e memória do futebol com site próprio. Ajuste moderado: serviço ao leitor, não pitch de apostas.'],
 ['Gremistas','https://www.gremistas.net/','CLUB_FAN','https://www.gremistas.net/noticias-do-gremio/gremio-quando-kannemann-marlon-diego-caito-dodi-voltam/','Quando jogadores voltam ao Grêmio?','https://www.gremistas.net/contato/','Cobertura gremista e agenda; oferecer recurso para consulta, sem repetir hipóteses de lesão.'],
 ['MKT Esportivo','https://www.mktesportivo.com/','FOOTBALL_MEDIA','https://www.mktesportivo.com/2026/09/corinthians-x-sao-paulo-ao-vivo-onde-assistir-a-final-do-brasileirao-feminino-2026/','Final do Brasileirão Feminino 2026: Corinthians x São Paulo','https://www.mktesportivo.com/contato','Marketing esportivo e futebol. Fit moderado; priorizar transparência de dados, não cupons ou publieditorial comprado.'],
 ['VAVEL Brasil','https://www.vavel.com/br/','MATCH_PREVIEW','https://www.vavel.com/br/futebol-internacional/2026/09/27/1273024-servia-x-holanda-pela-nations-league-onde-assistir-e-provaveis-escalacoes.html','Sérvia x Holanda pela Nations League','https://www.vavel.com/br/contact.html','Prévias e cobertura por repórteres; método de comparação pode complementar pauta sem reutilizar previsões.'],
 ['Diario de Pernambuco / Esportes DP','https://www.diariodepernambuco.com.br/esportes-dp/','REGIONAL','https://www.diariodepernambuco.com.br/esportes-dp/nautico/2026/09/11725030-nautico-domina-o-sport-nos-aflitos-e-vence-classico-pela-serie-b.html','Náutico vence o Sport nos Aflitos pela Série B','https://www.diariodepernambuco.com.br/esportes-dp/fale-conosco-esportes','Redação esportiva pernambucana; agenda e contexto de Sport, Náutico e Santa Cruz.'],
 ['Futebol Bahiano','https://futebolbaiano.com.br/','REGIONAL','https://futebolbaiano.com.br/2026/09/sem-11-jogadores-palmeiras-segue-preparacao-para-enfrentar-o-bahia.html','Palmeiras se prepara para enfrentar o Bahia','https://futebolbaiano.com.br/contato','Portal especializado no futebol da Bahia, útil para serviço de próximas partidas. Domínio antigo redireciona: não contar duas vezes.'],
];
const dates:Record<string,string>={'GOAL Brasil':'2026-06-12','Revista Colorada':'2026-09-26','APWin Brasil':'2026-09-26','UOL / Mauro Cezar Pereira':'2026-09-21','Nosso Palestra':'2026-09-26','São Paulo Blog':'2026-04-06','SuperVasco':'2026-09-26','FogãoNET':'2026-09-26','ecbahia':'2026-09-26','NETFLU':'2026-09-26','Meu Timão':'2026-09-26','Coluna do Fla':'2026-09-26','Trivela':'2026-09-27','Lance!':'2026-09-27','UmDois Esportes':'2026-09-26','NE45':'2026-09-26','Itatiaia':'2026-09-26','Esporte News Mundo':'2026-09-26','Gazeta Esportiva':'2026-09-26','Bahia Notícias':'2026-09-26','Footure':'2026-08-03','Gremistas':'2026-09-23','Verminosos por Futebol':'2025-11-09','MKT Esportivo':'2026-09-26','Futebol Bahiano':'2026-09-27','Diario de Pernambuco / Esportes DP':'2026-09-26'};
const emails:Record<string,string>={'NETVASCO':'netvasco@netvasco.com.br','GOAL Brasil':'brazildesk@goal.com','Itatiaia':'jornalismo@itatiaia.com.br','Esporte News Mundo':'redacao@esportenewsmundo.com.br','Correio da Bahia':'redacao@correio24horas.com.br'};
export const authorityProspects=entries.map(([name,site,category,articleUrl,articleTitle,contactUrl,fit])=>({name,url:site,category,angle:category==='NEWSLETTER_CREATOR'?'NEWSLETTER':category==='BETTING_EDITORIAL'||category==='DATA_ANALYTICS'?'DATA_CITATION':'JOURNALIST_RESOURCE',contactUrl,email:emails[name]??null,targetUrl:METHODOLOGY,notes:'Pesquisa pública em 27/09/2026. Título de referência resumido, não citação literal. Confirmar destinatário e pertinência antes de enviar. Nenhum contato realizado.',
 research:{country:'Brasil',language:'pt-BR',brazil:true,football:true,odds:category==='BETTING_EDITORIAL',editorial:true,active:!['São Paulo Blog','Verminosos por Futebol','GOAL Brasil'].includes(name),articleUrl,articleTitle,articleDate:dates[name]??null,sectionUrl:site,contactAlternative:name==='UOL / Mauro Cezar Pereira'?'Perfis profissionais listados no Linktree público; sem email confirmado.':'',evidenceUrl:site,checkedAt:'2026-09-27T12:00:00Z',audienceSignal:'NOT_AVAILABLE — sem estimativa independente de audiência',fit,linkability:category==='CLUB_FAN'?'Serviço ao torcedor; vínculo editorial depende da decisão da redação.':'Recurso de checagem/citação; interesse ainda não validado.',spamFlags:[],mentionStatus:'UNKNOWN',competitorEvidence:'NOT_AVAILABLE — nenhum gap presumido'} satisfies Research}));
