export const comparisonCopy={
  br:{title:'Comparar casas',intro:'As mesmas seleções, com todas as odds de uma única casa.',jump:'Comparar casas ↓',
    checking:'Consultando a comparação…',unavailable:'Comparação temporariamente indisponível. Tentaremos novamente.',
    empty:'Adicione seleções para comparar casas.',one:'Uma seleção: a odd combinada corresponde à sua odd individual.',
    noBookmaker:'Nenhuma casa verificada para comparação nesta região.',available:'Seleções disponíveis',combined:'Odd combinada',
    complete:'Todas as seleções disponíveis',partial:'Cobertura parcial',none:'Nenhuma seleção com preço atual',
    missing:'Seleções indisponíveis',best:'Melhor odd combinada entre as casas comparadas',tie:'Empate na melhor odd combinada entre as casas comparadas',
    noTotal:'Sem odd combinada: faltam preços válidos.',cta:'Ver odds',destination:'Abre o site da casa. Confira as seleções e as odds lá.',
    gated:'Link da casa indisponível.',disclosure:'Podemos receber comissão pelo link. Isso não altera a comparação.',
    summary:(complete:number,total:number)=>`${complete} de ${total} casas com todas as seleções disponíveis.`,
    updated:'Odd atualizada'},
  mx:{title:'Comparar casas',intro:'Las mismas selecciones, con todas las cuotas de una sola casa.',jump:'Comparar casas ↓',
    checking:'Consultando la comparación…',unavailable:'Comparación temporalmente no disponible. Volveremos a intentarlo.',
    empty:'Agrega selecciones para comparar casas.',one:'Una selección: la cuota combinada corresponde a su cuota individual.',
    noBookmaker:'No hay casas verificadas para comparar en esta región.',available:'Selecciones disponibles',combined:'Cuota combinada',
    complete:'Todas las selecciones disponibles',partial:'Cobertura parcial',none:'Ninguna selección con cuota vigente',
    missing:'Selecciones no disponibles',best:'Mejor cuota combinada entre las casas comparadas',tie:'Empate en la mejor cuota combinada entre las casas comparadas',
    noTotal:'Sin cuota combinada: faltan cuotas válidas.',cta:'Ver cuotas',destination:'Abre el sitio de la casa. Revisa las selecciones y las cuotas allí.',
    gated:'Enlace de la casa no disponible.',disclosure:'Podemos recibir una comisión por el enlace. Esto no altera la comparación.',
    summary:(complete:number,total:number)=>`${complete} de ${total} casas con todas las selecciones disponibles.`,
    updated:'Cuota actualizada'},
};
