import type {SlipUiLocale} from './localization';

export const comparisonCopy={
  br:{title:'Comparar casas',intro:'As mesmas seleções, com todas as odds de uma única casa.',jump:'Comparar casas ↓',
    checking:'Consultando a comparação…',unavailable:'Comparação temporariamente indisponível. Tentaremos novamente.',
    empty:'Adicione seleções para comparar casas.',one:'Uma seleção: a odd combinada corresponde à sua odd individual.',
    noBookmaker:'Nenhuma casa verificada para comparação nesta região.',available:'Seleções disponíveis',combined:'Odd combinada',
    complete:'Todas as seleções disponíveis',partial:'Indisponível para este cupom completo',none:'Nenhuma seleção com preço atual',
    missing:'Faltam',best:'Melhor retorno para este cupom',tie:'Empate no melhor retorno para este cupom',
    noTotal:'Indisponível para o cupom completo.',cta:'Ver odds',destination:'Abre o site da casa. Confira as seleções e as odds lá.',
    gated:'Link da casa indisponível.',disclosure:'Podemos receber comissão pelo link. Isso não altera a comparação.',
    potentialReturn:'Retorno potencial',difference:'Diferença vs melhor',oddsMayChange:'Cotações podem mudar na casa de apostas.',
    summary:(complete:number,total:number)=>`${complete} de ${total} casas com todas as seleções disponíveis.`,
    updated:'Odd atualizada'},
  mx:{title:'Comparar casas',intro:'Las mismas selecciones, con todas las cuotas de una sola casa.',jump:'Comparar casas ↓',
    checking:'Consultando la comparación…',unavailable:'Comparación temporalmente no disponible. Volveremos a intentarlo.',
    empty:'Agrega selecciones para comparar casas.',one:'Una selección: la cuota combinada corresponde a su cuota individual.',
    noBookmaker:'No hay casas verificadas para comparar en esta región.',available:'Selecciones disponibles',combined:'Cuota combinada',
    complete:'Todas las selecciones disponibles',partial:'No disponible para este cupón completo',none:'Ninguna selección con cuota vigente',
    missing:'Faltan',best:'Mejor retorno para este cupón',tie:'Empate en el mejor retorno para este cupón',
    noTotal:'No disponible para el cupón completo.',cta:'Ver cuotas',destination:'Abre el sitio de la casa. Revisa las selecciones y las cuotas allí.',
    gated:'Enlace de la casa no disponible.',disclosure:'Podemos recibir una comisión por el enlace. Esto no altera la comparación.',
    potentialReturn:'Retorno potencial',difference:'Diferencia vs el mejor',oddsMayChange:'Las cuotas pueden cambiar en la casa de apuestas.',
    summary:(complete:number,total:number)=>`${complete} de ${total} casas con todas las selecciones disponibles.`,
    updated:'Cuota actualizada'},
  en:{title:'Compare bookmakers',intro:'The same selections, using every price from a single bookmaker.',jump:'Compare bookmakers ↓',
    checking:'Loading the comparison…',unavailable:'Comparison is temporarily unavailable. We will try again.',
    empty:'Add selections to compare bookmakers.',one:'One selection: combined odds match that individual price.',
    noBookmaker:'No verified bookmakers to compare in this region.',available:'Available selections',combined:'Combined odds',
    complete:'Every selection available',partial:'Unavailable for this complete slip',none:'No selection with a current price',
    missing:'Missing',best:'Best return for this slip',tie:'Tied best return for this slip',
    noTotal:'Unavailable for complete slip',cta:'View odds',destination:'Opens the bookmaker site. Check the selections and odds there.',
    gated:'Bookmaker link unavailable.',disclosure:'We may receive a commission from the link. That does not change the comparison.',
    potentialReturn:'Potential return',difference:'Difference vs best',oddsMayChange:'Odds can change at the bookmaker.',
    summary:(complete:number,total:number)=>`${complete} of ${total} bookmakers have every selected outcome.`,
    updated:'Odds updated'},
} satisfies Record<SlipUiLocale,{summary:(complete:number,total:number)=>string;[key:string]:unknown}>;
