import {describe,it,expect,vi,afterEach} from 'vitest';
vi.mock('server-only',()=>({}));
import {outboundRequest,offersRequest,impressionRequest,legacyOutbound,type CommercialServices} from './server';
import {publicOffer,resolveOffer} from './service';
import {verifyOffer,clickDedup} from './tokens';
import {recordClick,recordImpression} from './analytics';
import {campaign,context,dependencies,key} from './fixtures.test-support';
import {geoAllowed} from './policy';
afterEach(()=>{vi.restoreAllMocks();vi.unstubAllEnvs();});
async function fixture(){const tasks:Array<()=>Promise<void>>=[],c=campaign(),deps=dependencies(c);const offer=(await resolveOffer(context(),deps))!,value=publicOffer(offer,key);
  const services:CommercialServices={deps,key,geo:()=>true,defer:fn=>{tasks.push(fn);},click:vi.fn().mockResolvedValue('id'),impression:vi.fn().mockResolvedValue(undefined)};
  const request=(extra:Record<string,string>={},suffix='')=>new Request('https://livasports.com'+value.href+suffix,{headers:{'sec-fetch-user':'?1','sec-fetch-mode':'navigate','sec-fetch-dest':'document','user-agent':'Browser',...extra}});
  return {tasks,c,deps,offer,value,services,request};}
describe('M8 canonical outbound and attribution',()=>{
  it.each(['GE','MX','US',''])('does not issue BR banner or odds offers to visitor country %s',async country=>{
    vi.stubEnv('VERCEL','1');vi.stubEnv('AFFILIATE_QA_GEO','BR');
    const f=await fixture();f.services.geo=geoAllowed;f.deps.campaigns=vi.fn(f.deps.campaigns);
    const contexts=[{locale:'br',bookmaker:'betsson',pagePath:'/br',placement:'home_right_rail'},
      {locale:'br',bookmaker:'betsson',pagePath:'/br/jogo/home-x-away-abcdef0123456789',placement:'match_odds_table',fixturePublicId:'abcdef0123456789',market:'MATCH_WINNER'}];
    const request=new Request('https://livasports.com/api/commercial/offers',{method:'POST',headers:{'content-type':'application/json','x-vercel-ip-country':country},body:JSON.stringify(contexts)});
    const response=await offersRequest(request,f.services);
    expect(response.status).toBe(200);expect(await response.json()).toEqual({offers:[null,null],providerRequests:0});
    const outbound=await outboundRequest(f.request({'x-vercel-ip-country':country}),'betsson','slip_bookmaker_comparison',f.services);
    expect(outbound.headers.get('location')??'').not.toContain('betsson.bet.br');expect(f.tasks).toHaveLength(0);
  });
  it('generates signed opaque context with no destination/operator campaign secret',async()=>{const f=await fixture();expect(verifyOffer(f.value.token,key)).toMatchObject({context:context(),campaignId:f.c.id});expect(f.value.token).not.toContain('approved');expect(JSON.stringify(f.value)).not.toContain('LOCAL_TEST_ONLY');expect(verifyOffer(f.value.token.slice(0,-1)+'Z',key)).toBeNull();expect(verifyOffer(f.value.token,'different-key')).toBeNull();expect(verifyOffer(f.value.token,key,Date.now()+400000)).toBeNull();});
  it('issues safe redirect before best-effort analytics and preserves attribution',async()=>{const f=await fixture(),fetch=vi.spyOn(globalThis,'fetch');const r=await outboundRequest(f.request(),'betsson','slip_bookmaker_comparison',f.services);expect(r.status).toBe(303);expect(r.headers.get('location')).toBe(f.c.destination);expect(r.headers.get('x-robots-tag')).toContain('noindex');expect(f.services.click).not.toHaveBeenCalled();expect(f.tasks).toHaveLength(1);await f.tasks[0]();expect(f.services.click).toHaveBeenCalledWith(expect.objectContaining({page:{pageType:'HOME',pagePath:'/br'},context:context(),campaign:f.c}),expect.stringMatching(/^[a-f0-9-]{36}$/),'HUMAN_CLICK',key);expect(fetch).not.toHaveBeenCalled();});
  it('analytics write failure and missing consent cannot prevent verified navigation',async()=>{const f=await fixture();vi.mocked(f.services.click).mockRejectedValue(new Error('private secret'));vi.spyOn(console,'warn').mockImplementation(()=>{});expect((await outboundRequest(f.request(),'betsson','slip_bookmaker_comparison',f.services)).status).toBe(303);await expect(f.tasks[0]()).resolves.toBeUndefined();f.tasks.length=0;expect((await outboundRequest(f.request({dnt:'1'}),'betsson','slip_bookmaker_comparison',f.services)).status).toBe(303);expect(f.tasks).toHaveLength(0);});
  it.each(['&url=https://evil.invalid','&destination=javascript%3Aalert(1)','&campaignId=override','&clickId=malformed','&offer=duplicate','&qa=arbitrary'])('rejects browser override %s',async suffix=>{const f=await fixture();expect((await outboundRequest(f.request({},suffix),'betsson','slip_bookmaker_comparison',f.services)).status).toBe(400);expect(f.tasks).toHaveLength(0);});
  it('rejects altered placement, bookmaker, GEO, disabled campaign, expired quote, and pricing failure',async()=>{for(const change of ['placement','bookmaker','geo','disabled','stale','failure']){const f=await fixture();if(change==='geo')f.services.geo=()=>false;if(change==='disabled')f.c.enabled=false;if(change==='stale')f.deps.pricing=async()=>null;if(change==='failure')f.deps.pricing=async()=>{throw Error('private');};
    const r=await outboundRequest(f.request(),change==='bookmaker'?'betano.bet.br':'betsson',change==='placement'?'match_odds_table':'slip_bookmaker_comparison',f.services);expect(r.headers.get('location')??'').not.toContain('betsson.bet.br');expect(f.tasks).toHaveLength(0);}});
  it('does not redirect or count HEAD, prefetch and bots; QA is separately classified',async()=>{const f=await fixture();for(const r of [new Request('https://livasports.com'+f.value.href,{method:'HEAD'}),f.request({purpose:'prefetch'}),f.request({'user-agent':'Googlebot'})])expect((await outboundRequest(r,'betsson','slip_bookmaker_comparison',f.services)).status).toBe(204);expect(f.tasks).toHaveLength(0);await outboundRequest(f.request({},'&qa=1'),'betsson','slip_bookmaker_comparison',f.services);await f.tasks[0]();expect(f.services.click).toHaveBeenCalledWith(expect.anything(),expect.any(String),'QA_TEST',key);});
  it('legacy safe links and programmatic requests never inflate human clicks',async()=>{const f=await fixture();expect((await legacyOutbound(f.request(),context(),f.services)).status).toBe(303);expect((await outboundRequest(new Request('https://livasports.com'+f.value.href),'betsson','slip_bookmaker_comparison',f.services)).status).toBe(303);expect(f.tasks).toHaveLength(0);});
  it('duplicates use a bounded first-party view window and idempotent SQL without PII',async()=>{const f=await fixture();expect(clickDedup('view',10001,key)).toBe(clickDedup('view',10009,key));expect(clickDedup('view',20001,key)).not.toBe(clickDedup('view',10001,key));const query=vi.fn().mockResolvedValue({rows:[]});await recordClick({query},f.offer,'view','QA_TEST',key,10001);await recordImpression({query},f.offer,'view','QA_TEST');expect(query.mock.calls[0][0]).toContain('ON CONFLICT(dedup_key) DO NOTHING');expect(query.mock.calls[1][0]).toContain('ON CONFLICT(id) DO NOTHING');expect(query.mock.calls[0][1][0]).toMatch(/^[a-f0-9-]{36}$/);expect(query.mock.calls.every(c=>!/\bip_hash\b|\buser_agent\b|\breferrer\b/.test(c[0]))).toBe(true);});
  it('validates rendered impressions, rejects inactive and forged tokens and never logs hidden SSR itself',async()=>{const f=await fixture();expect(f.tasks).toHaveLength(0);const body={eventId:'cccccccc-cccc-4ccc-8ccc-cccccccccccc',eventName:'affiliate_impression',offer:f.value.token};const r=new Request('https://livasports.com/api/events',{headers:{origin:'https://livasports.com','sec-fetch-site':'same-origin'}});
    expect((await impressionRequest(r,body,f.services)).status).toBe(204);await f.tasks[0]();expect(f.services.impression).toHaveBeenCalledWith(expect.anything(),expect.any(String),'HUMAN_VIEW');f.tasks.length=0;f.c.enabled=false;await impressionRequest(r,body,f.services);expect(f.tasks).toHaveLength(0);expect((await impressionRequest(r,{...body,campaignId:'override'},f.services)).status).toBe(400);expect((await impressionRequest(r,{...body,offer:'fake'},f.services)).status).toBe(400);});
  it('batches bounded campaign/page reads and never accepts extra canonical properties',async()=>{
    vi.stubEnv('AFFILIATE_QA_GEO','BR');
    const f=await fixture();f.deps.campaigns=vi.fn(f.deps.campaigns);f.deps.page=vi.fn(f.deps.page);const r=(body:unknown)=>new Request('https://livasports.com/api/commercial/offers',{method:'POST',headers:{'content-type':'application/json',origin:'https://livasports.com'},body:JSON.stringify(body)});
    const valid=await offersRequest(r([context(),context()]),f.services);expect(valid.status).toBe(200);expect((await valid.json()).offers).toHaveLength(2);expect(f.deps.campaigns).toHaveBeenCalledTimes(1);expect(f.deps.page).toHaveBeenCalledTimes(1);for(const body of [[],Array(17).fill(context()),[{...context(),campaignId:'override'}]])expect((await offersRequest(r(body),f.services)).status).toBe(400);});
});
