import type {InterfaceLocale} from './interface';
import type {LegalKind} from './legal-routes';
type Article={title:string;intro:string;sections:{title:string;body:string}[]};
export const legalReviewedAt='2026-09-16';
export const officialSafetySources={
  prevention:'https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/s/saude-mental/nao-aposte-sua-saude/prevencao-e-reducao-de-danos',
  exclusion:'https://www.gov.br/fazenda/pt-br/composicao/orgaos/secretaria-de-premios-e-apostas/autoexclusao',
  rules:'https://www.gov.br/fazenda/pt-br/assuntos/noticias/2026/julho/ministerio-da-fazenda-amplia-exigencias-de-publicidade-de-apostas-no-pais',
};
export const legalContent:Record<InterfaceLocale,Record<LegalKind,Article>>={
 br:{
  responsible:{title:'Jogo responsável',intro:'18+ · Apostar envolve risco de perda financeira e dependência. Você não precisa apostar para acompanhar o futebol.',sections:[
   {title:'Sua saúde vem primeiro',body:'Se apostar está afetando seu dinheiro, suas relações ou seu bem-estar, interrompa a atividade e procure apoio. No Brasil, uma Unidade Básica de Saúde (UBS) ou um Centro de Atenção Psicossocial (CAPS) pode orientar você.'},
   {title:'Autoexclusão no Brasil',body:'A plataforma oficial do Ministério da Fazenda permite solicitar o bloqueio do acesso às plataformas autorizadas abrangidas pelo sistema. A solicitação é feita diretamente no serviço público. A LivaSports não recebe documentos nem realiza esse pedido por você.'},
   {title:'Informação não é promessa',body:'Placares, estatísticas e resultados passados não garantem resultados futuros. Apostas não são fonte de renda nem investimento. Nunca use dinheiro destinado a despesas essenciais nem tente recuperar perdas apostando mais.'},
   {title:'Proteção de menores',body:'Apostas são proibidas para menores de 18 anos. O acesso a informações esportivas não autoriza a participação em apostas. Fora do Brasil, procure os serviços de saúde e de apoio da sua região.'},
  ]},
  disclosure:{title:'Divulgação de afiliados',intro:'A LivaSports publica informação esportiva e comparações e pode receber remuneração por publicidade ou links de afiliados.',sections:[
   {title:'Relação comercial',body:'Quando uma divulgação comercial está disponível, ela é identificada como Publicidade ou Patrocinado. Uma relação de afiliado pode gerar remuneração para a LivaSports conforme o contrato aplicável. A presença de uma marca não é recomendação para apostar.'},
   {title:'Dados esportivos e publicidade',body:'Classificação, resultados e estatísticas derivam dos dados armazenados das fontes esportivas. Uma parceria comercial não altera esses fatos. A disponibilidade de publicidade depende da região e da configuração da campanha, independentemente do idioma da interface.'},
   {title:'Ao sair do site',body:'Links externos levam a serviços com termos e políticas próprios. A LivaSports não aceita apostas, não mantém depósitos de apostas e não processa apostas ou pagamentos de apostadores. Cotações e condições de terceiros podem mudar.'},
  ]},
  terms:{title:'Termos de uso',intro:'A LivaSports é um serviço de informação esportiva, comparação e divulgação de afiliados. Estas informações explicam o uso atual do produto.',sections:[
   {title:'Uso das informações',body:'Consulte calendários, resultados, tabelas, perfis e estatísticas para acompanhar o esporte. A cobertura varia por competição, temporada e partida. Dados indisponíveis, participantes ainda não confirmados e atualizações atrasadas são identificados quando conhecidos.'},
   {title:'Limites dos dados',body:'Informações podem sofrer atrasos, correções ou interrupções. Não garantimos atualização instantânea nem cobertura integral de todos os eventos. O horário exibido segue a preferência selecionada; o calendário considera esse mesmo fuso horário.'},
   {title:'Serviços de terceiros',body:'A LivaSports não é uma casa de apostas. Não aceita apostas, não mantém depósitos de apostas e não processa apostas. Qualquer relação com um serviço externo é regida pelas condições desse serviço. O conteúdo não constitui aconselhamento financeiro nem promessa de ganho.'},
   {title:'Uso responsável do serviço',body:'Não tente contornar controles de acesso, extrair credenciais, interferir no funcionamento do site ou usar o serviço de modo ilícito. Nomes e imagens esportivas identificam suas respectivas entidades e não significam patrocínio ou endosso à LivaSports.'},
  ]},
  privacy:{title:'Privacidade',intro:'Este aviso descreve os dados utilizados pelo funcionamento atual da LivaSports. A navegação esportiva não exige uma conta de usuário.',sections:[
   {title:'Preferências no seu navegador',body:'Cookies próprios guardam seu idioma e fuso horário escolhidos por até um ano. Na interface em inglês, o fuso do dispositivo pode ser guardado por sete dias. Um registro temporário na sessão evita tentativas repetidas de detecção. Você pode mudar essas preferências nos controles do cabeçalho ou apagá-las nas configurações do navegador.'},
   {title:'Conteúdo salvo localmente',body:'Quando utilizado, o cupom de visitante fica no armazenamento local deste navegador. Mudar o idioma ou o fuso horário não apaga esse conteúdo. Apagar os dados locais do site também remove as preferências e o conteúdo salvo.'},
   {title:'Funcionamento e medição',body:'O site registra eventos de uso, como abertura de partida e visualização de seções, com contexto esportivo e idioma. A medição comercial pode registrar exibições e saídas por posicionamento e campanha. As tabelas de atribuição comercial não armazenam endereço IP, identificação do navegador ou endereço de origem. A hospedagem pode tratar dados técnicos necessários à entrega e à segurança das páginas.'},
   {title:'Preferências de privacidade e terceiros',body:'A medição comercial respeita os sinais DNT e GPC disponíveis no navegador. Em configurações que exigem consentimento, essa medição depende da permissão correspondente. Isso não significa que todos os registros técnicos ou eventos de uso sejam desativados. Imagens e conteúdo externo habilitado podem envolver solicitações a terceiros, sujeitos às políticas deles.'},
   {title:'Contas de usuário',body:'Entrar com Google ou com um link enviado por e-mail processa o endereço de e-mail, identificadores da conta no provedor, um identificador estável da conta LivaSports, nome e foto quando o provedor os envia, e identificadores de sessão. Esses dados autenticam você, mantêm a sessão neste navegador e exibem a página da conta. A sessão usa um cookie HttpOnly e um registro no banco, ambos com prazo de validade. Encerrar a sessão revoga o registro e apaga o cookie da conta; isso não altera o acesso privado de pré-visualização do proprietário. A exclusão da conta, quando disponível, remove a identidade e as sessões associadas; tokens de verificação não devem permanecer como identidade ativa. A navegação esportiva e o cupom de visitante continuam sem login.'},
  ]},
 },
 mx:{
  responsible:{title:'Juego responsable',intro:'18+ · Apostar implica riesgo de pérdidas económicas y dependencia. No necesitas apostar para seguir el fútbol.',sections:[
   {title:'Tu salud es lo primero',body:'Si las apuestas afectan tu dinero, tus relaciones o tu bienestar, interrumpe la actividad y busca apoyo profesional en tu localidad. Los recursos brasileños enlazados aquí están dirigidos a personas en Brasil.'},
   {title:'Autoexclusión en Brasil',body:'La plataforma oficial del Ministerio de Hacienda de Brasil permite solicitar el bloqueo de acceso a las plataformas autorizadas cubiertas por el sistema. La solicitud se realiza directamente en el servicio público. LivaSports no recibe documentos ni tramita solicitudes en tu nombre.'},
   {title:'La información no es una promesa',body:'Los marcadores, las estadísticas y los resultados anteriores no garantizan resultados futuros. Las apuestas no son una fuente de ingresos ni una inversión. No uses dinero para gastos esenciales ni intentes recuperar pérdidas apostando más.'},
   {title:'Protección de menores',body:'Las apuestas no son para menores de 18 años. Consultar información deportiva no autoriza a participar en apuestas. Si estás fuera de Brasil, acude a los servicios de salud y apoyo de tu región.'},
  ]},
  disclosure:{title:'Divulgación de afiliados',intro:'LivaSports publica información deportiva y comparaciones y puede recibir remuneración por publicidad o enlaces de afiliados.',sections:[
   {title:'Relación comercial',body:'Cuando hay contenido comercial disponible, se identifica como Publicidad o Patrocinado. Una relación de afiliación puede generar remuneración para LivaSports según el contrato correspondiente. La presencia de una marca no es una recomendación para apostar.'},
   {title:'Datos deportivos y publicidad',body:'Las clasificaciones, los resultados y las estadísticas proceden de los datos guardados de las fuentes deportivas. Una relación comercial no cambia estos hechos. La disponibilidad de publicidad depende de la región y la configuración de la campaña, independientemente del idioma.'},
   {title:'Al salir del sitio',body:'Los enlaces externos llevan a servicios con sus propios términos y políticas. LivaSports no acepta apuestas, no mantiene depósitos para apostar y no procesa apuestas ni pagos de apostadores. Las cuotas y condiciones de terceros pueden cambiar.'},
  ]},
  terms:{title:'Términos de uso',intro:'LivaSports es un servicio de información deportiva, comparación y divulgación de afiliados. Esta información explica el uso actual del producto.',sections:[
   {title:'Uso de la información',body:'Consulta calendarios, resultados, tablas, perfiles y estadísticas para seguir el deporte. La cobertura varía por competición, temporada y partido. Se indican los datos no disponibles, los participantes sin confirmar y las actualizaciones retrasadas cuando se conocen.'},
   {title:'Límites de los datos',body:'La información puede sufrir retrasos, correcciones o interrupciones. No garantizamos actualizaciones instantáneas ni cobertura completa de todos los eventos. Las horas y el calendario utilizan la misma zona horaria seleccionada.'},
   {title:'Servicios de terceros',body:'LivaSports no es una casa de apuestas. No acepta apuestas, no mantiene depósitos para apostar y no procesa apuestas. Cualquier relación con un servicio externo se rige por sus condiciones. El contenido no es asesoría financiera ni una promesa de ganancias.'},
   {title:'Uso responsable del servicio',body:'No intentes eludir controles de acceso, extraer credenciales, interferir con el sitio ni utilizarlo de forma ilícita. Los nombres e imágenes deportivos identifican a sus respectivas entidades y no implican patrocinio ni respaldo a LivaSports.'},
  ]},
  privacy:{title:'Privacidad',intro:'Este aviso describe los datos utilizados por el funcionamiento actual de LivaSports. La navegación deportiva no requiere una cuenta.',sections:[
   {title:'Preferencias del navegador',body:'Las cookies propias guardan el idioma y la zona horaria elegidos hasta un año. En la interfaz en inglés, la zona del dispositivo puede guardarse durante siete días. Un registro temporal de sesión evita intentos repetidos de detección. Puedes cambiar estas preferencias en el encabezado o eliminarlas desde la configuración del navegador.'},
   {title:'Contenido guardado localmente',body:'Cuando se utiliza, el cupón de visitante queda en el almacenamiento local de este navegador. Cambiar de idioma o zona horaria no lo elimina. Borrar los datos locales del sitio elimina las preferencias y el contenido guardado.'},
   {title:'Funcionamiento y medición',body:'El sitio registra eventos de uso, como la apertura de un partido y la visualización de secciones, con contexto deportivo e idioma. La medición comercial puede registrar visualizaciones y salidas por ubicación y campaña. Las tablas de atribución comercial no guardan direcciones IP, identificación del navegador ni direcciones de origen. El alojamiento puede tratar datos técnicos necesarios para entregar y proteger las páginas.'},
   {title:'Privacidad y terceros',body:'La medición comercial respeta las señales DNT y GPC disponibles en el navegador. Si la configuración requiere consentimiento, esa medición depende del permiso correspondiente. Esto no significa que se desactiven todos los registros técnicos o eventos de uso. Las imágenes y el contenido externo habilitado pueden generar solicitudes a terceros, sujetas a sus políticas.'},
   {title:'Cuentas de usuario',body:'Iniciar sesión con Google o con un enlace enviado por correo procesa la dirección de correo, identificadores de la cuenta en el proveedor, un identificador estable de la cuenta LivaSports, nombre y foto cuando el proveedor los envía, e identificadores de sesión. Estos datos autentican, mantienen la sesión en este navegador y muestran la página de cuenta. La sesión usa una cookie HttpOnly y un registro en la base de datos, ambos con fecha de caducidad. Cerrar sesión revoca el registro y borra la cookie de cuenta; no altera el acceso privado de previsualización del propietario. La eliminación de la cuenta, cuando esté disponible, quita la identidad y las sesiones asociadas; los tokens de verificación no deben permanecer como identidad activa. La navegación deportiva y el cupón de visitante siguen sin iniciar sesión.'},
  ]},
 },
 en:{
  responsible:{title:'Responsible gambling',intro:'18+ · Gambling carries risks of financial loss and addiction. You do not need to gamble to follow football.',sections:[
   {title:'Your health comes first',body:'If gambling is affecting your finances, relationships or wellbeing, stop and seek professional support locally. The Brazilian resources linked here are intended for people in Brazil.'},
   {title:'Self-exclusion in Brazil',body:'Brazil’s official Ministry of Finance service lets people request blocked access to the authorized platforms covered by its system. Apply directly through the public service. LivaSports does not collect documents or submit applications for you.'},
   {title:'Information is not a promise',body:'Scores, statistics and previous results do not guarantee future outcomes. Gambling is not income or an investment. Do not use money needed for essentials or try to recover losses by gambling more.'},
   {title:'Protecting minors',body:'Gambling is not for anyone under 18. Access to sports information does not authorize gambling. Outside Brazil, use health and support services in your own region.'},
  ]},
  disclosure:{title:'Affiliate disclosure',intro:'LivaSports publishes sports information and comparisons and may earn revenue from advertising or affiliate links.',sections:[
   {title:'Commercial relationships',body:'Available commercial content is marked Advertisement or Sponsored. An affiliate relationship may generate revenue for LivaSports under the applicable agreement. The presence of a brand is not a recommendation to gamble.'},
   {title:'Sports facts and advertising',body:'Standings, results and statistics come from stored sports-source data. A commercial relationship does not change those facts. Advertising availability depends on region and campaign configuration, independently of interface language.'},
   {title:'Leaving the site',body:'External links lead to services with their own terms and policies. LivaSports does not accept bets, hold betting deposits or process wagers or bettor payments. Third-party prices and conditions can change.'},
  ]},
  terms:{title:'Terms of use',intro:'LivaSports is a sports information, comparison and affiliate publishing service. This information explains the product as it currently works.',sections:[
   {title:'Using the information',body:'Explore schedules, results, tables, profiles and statistics to follow sport. Coverage varies by competition, season and match. Unavailable data, unconfirmed participants and delayed updates are identified when known.'},
   {title:'Data limitations',body:'Information can be delayed, corrected or interrupted. We do not guarantee instant updates or complete coverage of every event. Displayed times and the calendar use the same selected time zone.'},
   {title:'Third-party services',body:'LivaSports is not a bookmaker. It does not accept bets, hold betting deposits or process wagers. Any relationship with an external service is governed by that service’s terms. Content is not financial advice or a promise of winnings.'},
   {title:'Responsible use of the service',body:'Do not bypass access controls, extract credentials, disrupt the site or use it unlawfully. Sports names and images identify their respective entities and do not imply sponsorship or endorsement of LivaSports.'},
  ]},
  privacy:{title:'Privacy',intro:'This notice describes data used by the current LivaSports product. Browsing sports information does not require an account.',sections:[
   {title:'Browser preferences',body:'First-party cookies remember your chosen language and time zone for up to one year. The English interface may remember your device time zone for seven days. A temporary session record prevents repeated detection attempts. Change these preferences in the header or remove them using your browser settings.'},
   {title:'Locally saved content',body:'When used, the guest slip is saved in this browser’s local storage. Changing language or time zone does not erase it. Clearing this site’s local data also removes saved content and preferences.'},
   {title:'Operation and measurement',body:'The site records usage events such as opening a match and viewing sections, with sports context and language. Commercial measurement may record views and outbound activity by placement and campaign. Commercial attribution tables do not store IP addresses, browser identification or referrer addresses. The hosting service may process technical data needed to deliver and secure pages.'},
   {title:'Privacy preferences and third parties',body:'Commercial measurement respects available browser DNT and GPC signals. In configurations requiring consent, that measurement depends on the corresponding permission. This does not mean all technical logs or usage events are disabled. Images and enabled external content may involve requests to third parties under their own policies.'},
   {title:'User accounts',body:'Signing in with Google or an emailed link processes your email address, provider account identifiers, a stable LivaSports user identifier, display name and photo when the provider sends them, and session identifiers. These data authenticate you, keep the session on this browser and render the account page. The session uses an HttpOnly cookie and a database record, both with an expiry. Signing out revokes the record and clears the account cookie; it does not change private owner preview access. Account deletion, when available, removes the identity and associated sessions; verification tokens must not remain as active identity. Sports browsing and the guest slip still work without signing in.'},
  ]},
 },
};
export const safetyCopy={br:{warning:'Ministério da Fazenda adverte: Apostar pode causar dependência',footer:'Informação esportiva, comparação e divulgação de afiliados. A LivaSports não aceita apostas, não mantém depósitos de apostas e não processa apostas.',sources:'Recursos oficiais do Brasil',health:'Prevenção e apoio à saúde',exclusion:'Autoexclusão oficial',rules:'Regras de publicidade no Brasil',reviewed:'Atualizado em',navigation:'Informações e políticas'},mx:{warning:'Apostar puede causar dependencia y pérdidas económicas.',footer:'Información deportiva, comparación y divulgación de afiliados. LivaSports no acepta apuestas, no mantiene depósitos para apostar y no procesa apuestas.',sources:'Recursos oficiales de Brasil',health:'Prevención y apoyo a la salud',exclusion:'Autoexclusión oficial en Brasil',rules:'Reglas de publicidad de Brasil',reviewed:'Actualizado el',navigation:'Información y políticas'},en:{warning:'Gambling can cause addiction and financial loss.',footer:'Sports information, comparison and affiliate publishing. LivaSports does not accept bets, hold betting deposits or process wagers.',sources:'Official resources in Brazil',health:'Prevention and health support',exclusion:'Official Brazilian self-exclusion',rules:'Brazilian advertising rules',reviewed:'Updated',navigation:'Information and policies'}};
